# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 50
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
     # ignore all GitHub linguist patch updates
      - dependency-name: "@sentry/react-native"
      - dependency-name: "sentry-expo"
      - dependency-name: "react-native"
      - dependency-name: "@babel/core"
      - dependency-name: "husky"