name: Test, Build and Release

on:
 push:
   branches: [ main ]

jobs:
  check:
    name: Lint, Format, Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint check
        run: yarn lint

      - name: Format check
        run: yarn prettier:check

      - name: Unit & Integration tests
        run: yarn test:ci

      - name: Install concurrently
        run: npm install -g concurrently

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Install playwright
        run: yarn playwright install

      # - name: Smoke & Acceptance tests
      #   run: |
      #     yarn build:storybook --quiet
      #       npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
      #         "npx http-server storybook-static --port 6006 --silent" \
      #         "npx wait-on tcp:127.0.0.1:6006 && yarn test:storybook"
  release:
    name: Release
    needs: check
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Use node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Install dependencies
        run: npm pkg delete scripts.prepare && rm -rf .husky/.pre-push && yarn install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release@22 --omit=dev --ignore-scripts